"""empty message

Revision ID: 0e5a7386f3b0
Revises: 99beb49b34f3
Create Date: 2019-10-17 16:17:32.136352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e5a7386f3b0'
down_revision = '99beb49b34f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('events', 'gender',
    #            existing_type=sa.TEXT(),
    #            nullable=False)
    # op.alter_column('events', 'name',
    #            existing_type=sa.TEXT(),
    #            nullable=False)
    # op.alter_column('events', 'type',
    #            existing_type=sa.TEXT(),
    #            nullable=False)
    # op.alter_column('events', 'weapon',
    #            existing_type=sa.TEXT(),
    #            nullable=False)
    # op.create_foreign_key(None, 'events', 'tournaments', ['tournament_id'], ['id_'])
    op.add_column('tournaments', sa.Column('closes', sa.DateTime(), nullable=True))
    op.add_column('tournaments', sa.Column('opens', sa.DateTime(), nullable=True))
    op.add_column('tournaments', sa.Column('withdraw', sa.DateTime(), nullable=True))
    #op.drop_column('users', 'member')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('member', sa.INTEGER(), nullable=True))
    op.drop_column('tournaments', 'withdraw')
    op.drop_column('tournaments', 'opens')
    op.drop_column('tournaments', 'closes')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.alter_column('events', 'weapon',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('events', 'type',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('events', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('events', 'gender',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
