"""empty message

Revision ID: 25044eae12b7
Revises: 8b7b5391760b
Create Date: 2019-11-18 21:18:27.013180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25044eae12b7'
down_revision = '8b7b5391760b'
branch_labels = None
depends_on = None


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('delete_me', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'delete_me')
    # ### end Alembic commands ###
