"""FK user added to members table

Revision ID: 5860ffef09f4
Revises: dcfe465adbe2
Create Date: 2019-10-03 11:55:57.782813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5860ffef09f4'
down_revision = 'dcfe465adbe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('members', sa.Column('user_id', sa.Integer(), nullable=True))
    table_name = ('members')
    with op.batch_alter_table(table_name) as batch:
        # op.create_foreign_key(None, 'members', 'users', ['user_id'], ['id'])
   
        batch.create_foreign_key(table_name, 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_column('members', 'user_id')
    # ### end Alembic commands ###
