"""add abbreviation and status to Event

Revision ID: 99beb49b34f3
Revises: 1130d49e2c02
Create Date: 2019-10-09 23:19:58.637692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99beb49b34f3'
down_revision = '1130d49e2c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('events', sa.Column('abbreviation', sa.String(length=3), nullable=True))
    op.add_column('events', sa.Column('status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  #  op.drop_column('events', 'status')
    op.drop_column('events', 'abbreviation')
    # ### end Alembic commands ###
