"""empty message

Revision ID: a485de8c06db
Revises: 7fa9b0f30ee7
Create Date: 2019-11-18 23:14:33.566578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a485de8c06db'
down_revision = '7fa9b0f30ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('delete_me', sa.String(length=5), nullable=True))
    op.alter_column('events', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('events', 'delete_me')
    # ### end Alembic commands ###
