"""add member FK to User table

Revision ID: ec2a189f0744
Revises: 5860ffef09f4
Create Date: 2019-10-03 23:17:26.192320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec2a189f0744'
down_revision = '5860ffef09f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    table_name = 'members'
    with op.batch_alter_table(table_name) as batch:
        batch.drop_constraint('members', type_='foreignkey')
        batch.drop_column('user_id')
    table_name = 'users'
    with op.batch_alter_table(table_name) as batch:
        batch.add_column( sa.Column('member', sa.Integer(), nullable=True))
        batch.create_foreign_key('users', 'members', ['member'], ['id_'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'member')
    op.add_column('members', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key('members', 'members', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
